/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package halaman;

/**
 *
 * @author ZAKI
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pasien_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        dokter_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        tescov19_btn = new javax.swing.JButton();
        rawatinap_cov19_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        konsultasi_btn = new javax.swing.JButton();
        rawatinap_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pembayaran_btn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dbRSU 1.png"))); // NOI18N
        jLabel1.setLabelFor(this);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pasien_btn.setText("Pasien");
        pasien_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasien_btnActionPerformed(evt);
            }
        });
        getContentPane().add(pasien_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 180, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("ISI DATA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 1950, 10));

        dokter_btn.setText("Dokter");
        dokter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dokter_btnActionPerformed(evt);
            }
        });
        getContentPane().add(dokter_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 180, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("LAYANAN COVID-19");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 310, -1, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 360, 20, 420));

        tescov19_btn.setText("Uji Test Covid-19");
        tescov19_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tescov19_btnActionPerformed(evt);
            }
        });
        getContentPane().add(tescov19_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 410, 190, 50));

        rawatinap_cov19_btn.setText("Rawat Inap Covid-19");
        rawatinap_cov19_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rawatinap_cov19_btnActionPerformed(evt);
            }
        });
        getContentPane().add(rawatinap_cov19_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 500, 190, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("LAYANAN REGULER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));

        konsultasi_btn.setText("Konsultasi");
        konsultasi_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konsultasi_btnActionPerformed(evt);
            }
        });
        getContentPane().add(konsultasi_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 180, 50));

        rawatinap_btn.setText("Rawat Inap Reguler");
        rawatinap_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rawatinap_btnActionPerformed(evt);
            }
        });
        getContentPane().add(rawatinap_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, 180, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("PEMBAYARAN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1610, 310, -1, -1));

        pembayaran_btn.setText("Pembayaran");
        pembayaran_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaran_btnActionPerformed(evt);
            }
        });
        getContentPane().add(pembayaran_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 400, 190, 50));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 20, 420));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 360, 20, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pasien_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasien_btnActionPerformed
        // TODO add your handling code here:
        pasien p = new pasien();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pasien_btnActionPerformed

    private void dokter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dokter_btnActionPerformed
        // TODO add your handling code here:
        dokter d = new dokter();
        d.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_dokter_btnActionPerformed

    private void konsultasi_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konsultasi_btnActionPerformed
        // TODO add your handling code here:
        resep_konsultasi_dokter rkd = new resep_konsultasi_dokter();
        rkd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_konsultasi_btnActionPerformed

    private void rawatinap_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rawatinap_btnActionPerformed
        // TODO add your handling code here:
        ruang_rawat_inap_reguler reg = new ruang_rawat_inap_reguler();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_rawatinap_btnActionPerformed

    private void tescov19_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tescov19_btnActionPerformed
        // TODO add your handling code here:
        tes_covid19 tes = new tes_covid19();
        tes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tescov19_btnActionPerformed

    private void rawatinap_cov19_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rawatinap_cov19_btnActionPerformed
        // TODO add your handling code here:
        ruang_rawat_inap_covid19 cov = new ruang_rawat_inap_covid19();
        cov.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_rawatinap_cov19_btnActionPerformed

    private void pembayaran_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaran_btnActionPerformed
        // TODO add your handling code here:
        pembayaran byr = new pembayaran();
        byr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pembayaran_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dokter_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton konsultasi_btn;
    private javax.swing.JButton pasien_btn;
    private javax.swing.JButton pembayaran_btn;
    private javax.swing.JButton rawatinap_btn;
    private javax.swing.JButton rawatinap_cov19_btn;
    private javax.swing.JButton tescov19_btn;
    // End of variables declaration//GEN-END:variables
}
