/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package halaman;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZAKI
 */
public class pasien extends javax.swing.JFrame {

    /**
     * Creates new form pasien
     */
    private void kosongkan_form(){
        idpasien_txt.setEditable(true);
        idpasien_txt.setText(null);
        nama_txt.setText(null);
        gender_txt.setSelectedIndex(0);
        usia_txt.setText(null);
        alamat_txt.setText(null);;
        notelp_txt.setText(null);
        keluhan_txt.setText(null);
        //idstatus_txt.setText(null);
        //idresep_txt.setText(null);

        }
      
    private void tampilkan_data(){
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("No.");
        model.addColumn("NIK");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Usia");
        model.addColumn("Alamat");
        model.addColumn("No. Telepon");    
        model.addColumn("Keluhan / Penyakit");
        //model.addColumn("Id Status Covid19");   
        //model.addColumn("No. Resep Dokter ");
        
 
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
       try{
           int no = 1;
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "SELECT * FROM pasien";
            
            java.sql.ResultSet res = s.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
                
            }
            tabeldata.setModel(model);
        }catch(Exception e){
            e.printStackTrace();
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    
    
    
    public pasien() {
        initComponents();
        tampilkan_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idpasien_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nama_txt = new javax.swing.JTextField();
        gender_txt = new javax.swing.JComboBox<>();
        usia_txt = new javax.swing.JTextField();
        alamat_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        keluhan_txt = new javax.swing.JTextArea();
        notelp_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        hapus = new javax.swing.JButton();
        update = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cari_btn = new javax.swing.JButton();
        search_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        count_btn = new javax.swing.JButton();
        count_txt = new javax.swing.JTextField();
        kembali_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dbRSU 1.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("ID Pasien          :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Nama Pasien       :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Jenis Kelamin      :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Usia Pasien          :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Alamat Pasien      :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("No. Telepon         :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Keluhan / Penyakit :");

        gender_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        gender_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender_txtActionPerformed(evt);
            }
        });

        keluhan_txt.setColumns(20);
        keluhan_txt.setRows(5);
        jScrollPane1.setViewportView(keluhan_txt);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("IDENTITAS PASIEN");

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabeldata);

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hapus.png"))); // NOI18N
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/update.png"))); // NOI18N
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save.png"))); // NOI18N
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("TABEL DATA PASIEN");

        cari_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cari.png"))); // NOI18N
        cari_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_btnActionPerformed(evt);
            }
        });

        jLabel10.setText("*Cari Data Berdasarkan ID Pasien");

        count_btn.setText("Jumlah Pasien");
        count_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                count_btnActionPerformed(evt);
            }
        });

        kembali_btn.setText("Kembali");
        kembali_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel9)
                .addGap(462, 462, 462)
                .addComponent(jLabel12)
                .addGap(50, 50, 50)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cari_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(count_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(count_btn)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1946, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(32, 32, 32)
                                .addComponent(idpasien_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(19, 19, 19)
                                .addComponent(nama_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(17, 17, 17)
                                .addComponent(gender_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(15, 15, 15)
                                .addComponent(usia_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(15, 15, 15)
                                .addComponent(alamat_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(20, 20, 20)
                                .addComponent(notelp_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(225, 225, 225)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kembali_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addComponent(kembali_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cari_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(count_btn)
                        .addComponent(count_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2))
                            .addComponent(idpasien_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel3))
                            .addComponent(nama_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel4))
                            .addComponent(gender_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5))
                            .addComponent(usia_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6))
                            .addComponent(alamat_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel7))
                            .addComponent(notelp_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hapus)
                    .addComponent(update)
                    .addComponent(simpan))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gender_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gender_txtActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "DELETE FROM pasien WHERE Id_pasien='"+idpasien_txt.getText()+"'";
            
            s.execute(sql);
            //System.out.println("Data berhasil dihapus!");
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data gagal dihapus!");
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_hapusActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "INSERT INTO pasien VALUES"+"("+idpasien_txt.getText()+",'"+nama_txt.getText()+"','"+gender_txt.getSelectedItem()+"',"+usia_txt.getText()+",'"+alamat_txt.getText()+"','"+notelp_txt.getText()+"','"+keluhan_txt.getText()+"')";
            s.execute(sql);
            //System.out.println("Data berhasil disimpan!");
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
            
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data gagal disimpan!");
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_simpanActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "UPDATE pasien SET Id_pasien='"+idpasien_txt.getText()+"',Nama_pasien='"+nama_txt.getText()+"',Gender_pasien='"+gender_txt.getSelectedItem()+"',Usia_pasien='"+usia_txt.getText()+"',Alamat_pasien='"+alamat_txt.getText()+"',No_telp_pasien='"+notelp_txt.getText()+"',Keluhan='"+keluhan_txt.getText()+"' WHERE Id_pasien='"+idpasien_txt.getText()+"'";
            
            s.execute(sql);
            //System.out.println("Data berhasil diperbarui!");
            JOptionPane.showMessageDialog(null, "Data berhasil diperbarui!");
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data gagal diperbarui!");
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_updateActionPerformed

    private void cari_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_btnActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            ResultSet rs;
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "SELECT*FROM pasien WHERE Id_pasien='"+search_txt.getText()+"'";
            rs = s.executeQuery(sql);
            if(rs.next()){
                String Id_pasien = rs.getString("Id_pasien");
                String Nama_pasien = rs.getString("Nama_pasien");
                String Gender_pasien = rs.getString("Gender_pasien");
                String Usia_pasien = rs.getString("Usia_pasien");
                String Alamat_pasien = rs.getString("Alamat_pasien");
                String No_telp_pasien = rs.getString("No_telp_pasien");
                String Keluhan = rs.getString("Keluhan");
                
                idpasien_txt.setText(Id_pasien);
                nama_txt.setText(Nama_pasien);
                gender_txt.setSelectedItem(Gender_pasien);
                usia_txt.setText(Usia_pasien);
                alamat_txt.setText(Alamat_pasien);;
                notelp_txt.setText(No_telp_pasien);
                keluhan_txt.setText(Keluhan);
            }
            JOptionPane.showMessageDialog(null,"Data berhasil ditemukan!");
            
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        tampilkan_data();
    }//GEN-LAST:event_cari_btnActionPerformed

    private void count_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_count_btnActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            ResultSet rs;
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "SELECT COUNT(*) FROM pasien";
            rs = s.executeQuery(sql);
            if(rs.next()){
                String count = rs.getString("count(*)");
                
                count_txt.setText(count);
            }
            //JOptionPane.showMessageDialog(null,"Data Berhasil Dicari!");
            
        }catch(Exception e){
            e.printStackTrace();
            //JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_count_btnActionPerformed

    private void kembali_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali_btnActionPerformed
        // TODO add your handling code here:
        menu m = new menu();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kembali_btnActionPerformed

    private void tabeldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldataMouseClicked
        // TODO add your handling code here:
        int baris = tabeldata.rowAtPoint(evt.getPoint());
        
        String Id_pasien = tabeldata.getValueAt(baris,1).toString();
        idpasien_txt.setText(Id_pasien);
        
        String Nama_pasien = tabeldata.getValueAt(baris,2).toString();
        nama_txt.setText(Nama_pasien);
        
        String Gender_pasien = tabeldata.getValueAt(baris,3).toString();
        gender_txt.setSelectedItem(Gender_pasien);
        
        String Usia_pasien = tabeldata.getValueAt(baris,4).toString();
        usia_txt.setText(Usia_pasien);
        
        String Alamat_pasien = tabeldata.getValueAt(baris,5).toString();
        alamat_txt.setText(Alamat_pasien);;
        
        String No_telp_pasien = tabeldata.getValueAt(baris,6).toString();
        notelp_txt.setText(No_telp_pasien);
        
        String Keluhan = tabeldata.getValueAt(baris,7).toString();
        keluhan_txt.setText(Keluhan);
        
    }//GEN-LAST:event_tabeldataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat_txt;
    private javax.swing.JButton cari_btn;
    private javax.swing.JButton count_btn;
    private javax.swing.JTextField count_txt;
    private javax.swing.JComboBox<String> gender_txt;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField idpasien_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea keluhan_txt;
    private javax.swing.JButton kembali_btn;
    private javax.swing.JTextField nama_txt;
    private javax.swing.JTextField notelp_txt;
    private javax.swing.JTextField search_txt;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabeldata;
    private javax.swing.JButton update;
    private javax.swing.JTextField usia_txt;
    // End of variables declaration//GEN-END:variables
}
