/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package halaman;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZAKI
 */
public class pembayaran extends javax.swing.JFrame {

    private void kosongkan_form(){
        idbayar_txt.setEditable(true);
        idbayar_txt.setText(null);
        idpasien_txt.setText(null);
        tgl_txt.setText(null);;
        total_txt.setText(null);

        }
      
    private void tampilkan_data(){
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("No.");
        model.addColumn("Kode Pembayaran");
        model.addColumn("ID Pasien");
        model.addColumn("Tanggal Bayar");
        model.addColumn("Total Biaya");    
        
 
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
       try{
           int no = 1;
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "SELECT * FROM pembayaran";
            
            java.sql.ResultSet res = s.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4)});
                
            }
            tabeldata.setModel(model);
        }catch(Exception e){
            e.printStackTrace();
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    public pembayaran() {
        initComponents();
        tampilkan_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idbayar_txt = new javax.swing.JTextField();
        idpasien_txt = new javax.swing.JTextField();
        tgl_txt = new javax.swing.JTextField();
        total_txt = new javax.swing.JTextField();
        hapus = new javax.swing.JButton();
        update = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        search_txt = new javax.swing.JTextField();
        cari_btn = new javax.swing.JButton();
        kembali_btn = new javax.swing.JButton();
        count_btn = new javax.swing.JButton();
        count_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dbRSU 1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Pembayaran");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 344, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 393, 1946, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Kode Pembayaran     :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 424, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("ID Pasien                   :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 478, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Tanggal Pembayaran :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 532, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Total Biaya               :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 586, -1, -1));

        idbayar_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbayar_txtActionPerformed(evt);
            }
        });
        getContentPane().add(idbayar_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 421, 300, -1));
        getContentPane().add(idpasien_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 475, 300, -1));
        getContentPane().add(tgl_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 529, 298, -1));
        getContentPane().add(total_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 583, 298, -1));

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hapus.png"))); // NOI18N
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 774, 151, -1));

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/update.png"))); // NOI18N
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 774, 121, -1));

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save.png"))); // NOI18N
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 774, 121, -1));

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeldata);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 393, 1238, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Tabel Data Pembayaran");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 344, -1, -1));

        jLabel8.setText("*Cari Data Berdasarkan Kode Pembayaran");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(995, 352, -1, -1));
        getContentPane().add(search_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 349, 190, -1));

        cari_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cari.png"))); // NOI18N
        cari_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_btnActionPerformed(evt);
            }
        });
        getContentPane().add(cari_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1518, 344, 90, 40));

        kembali_btn.setText("Kembali");
        kembali_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali_btnActionPerformed(evt);
            }
        });
        getContentPane().add(kembali_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 306, -1, -1));

        count_btn.setText("Jumlah Data");
        count_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                count_btnActionPerformed(evt);
            }
        });
        getContentPane().add(count_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1810, 350, -1, -1));
        getContentPane().add(count_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1720, 350, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idbayar_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbayar_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbayar_txtActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "INSERT INTO pembayaran VALUES"+"('"+idbayar_txt.getText()+"',"+idpasien_txt.getText()+",'"+tgl_txt.getText()+"',"+total_txt.getText()+")";
            s.execute(sql);
            //System.out.println("Record Inserted Successfully!");
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
            
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data gagal disimpan!");
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_simpanActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "UPDATE pembayaran SET Id_pembayaran='"+idbayar_txt.getText()+"',Id_pasien='"+idpasien_txt.getText()+"',Tgl_bayar='"+tgl_txt.getText()+"',Total_biaya='"+total_txt.getText()+"'"+" WHERE Id_pembayaran='"+idbayar_txt.getText()+"'";
            
            s.execute(sql);
            //System.out.println("Data berhasil diperbarui!");
            JOptionPane.showMessageDialog(null, "Data berhasil diperbarui!");
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data gagal diperbarui!");
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_updateActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "DELETE FROM pembayaran WHERE Id_pembayaran='"+idbayar_txt.getText()+"'";
            
            s.execute(sql);
            //System.out.println("Data berhasil dihapus!");
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data gagal dihapus!");
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_hapusActionPerformed

    private void cari_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_btnActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            ResultSet rs;
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "SELECT*FROM pembayaran WHERE Id_pembayaran='"+search_txt.getText()+"'";
            rs = s.executeQuery(sql);
            if(rs.next()){
                String Id_pembayaran = rs.getString("Id_pembayaran");
                String Id_pasien = rs.getString("Id_pasien");
                String Tgl_bayar = rs.getString("Tgl_bayar");
                String Total_biaya = rs.getString("Total_biaya");
                
                
                idbayar_txt.setText(Id_pembayaran);
                idpasien_txt.setText(Id_pasien);
                tgl_txt.setText(Tgl_bayar);;
                total_txt.setText(Total_biaya);
                
            }
            JOptionPane.showMessageDialog(null,"Data berhasil ditemukan!");
            
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        tampilkan_data();
    }//GEN-LAST:event_cari_btnActionPerformed

    private void kembali_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali_btnActionPerformed
        // TODO add your handling code here:
        menu m = new menu();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kembali_btnActionPerformed

    private void count_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_count_btnActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            ResultSet rs;
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "SELECT COUNT(*) FROM pembayaran";
            rs = s.executeQuery(sql);
            if(rs.next()){
                String count = rs.getString("count(*)");
                
                count_txt.setText(count);
            }
            //JOptionPane.showMessageDialog(null,"Data Berhasil Dicari!");
            
        }catch(Exception e){
            e.printStackTrace();
            //JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_count_btnActionPerformed

    private void tabeldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldataMouseClicked
        // TODO add your handling code here:
        int baris = tabeldata.rowAtPoint(evt.getPoint());
        
        String Id_pembayaran = tabeldata.getValueAt(baris,1).toString();
        idbayar_txt.setText(Id_pembayaran);
        
        String Id_pasien = tabeldata.getValueAt(baris,2).toString();
        idpasien_txt.setText(Id_pasien);
        
        String Tgl_bayar = tabeldata.getValueAt(baris,3).toString();
        tgl_txt.setText(Tgl_bayar);
        
        String Total_biaya = tabeldata.getValueAt(baris,4).toString();
        total_txt.setText(Total_biaya);
        
        
    }//GEN-LAST:event_tabeldataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari_btn;
    private javax.swing.JButton count_btn;
    private javax.swing.JTextField count_txt;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField idbayar_txt;
    private javax.swing.JTextField idpasien_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton kembali_btn;
    private javax.swing.JTextField search_txt;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabeldata;
    private javax.swing.JTextField tgl_txt;
    private javax.swing.JTextField total_txt;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
