/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package halaman;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZAKI
 */
public class rapid_test extends javax.swing.JFrame {

    private void kosongkan_form(){
        idrapid_txt.setEditable(true);
        idrapid_txt.setText(null);
        hasil_txt.setSelectedIndex(0);
        biaya_txt.setText(null);
        

        }
      
    private void tampilkan_data(){
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("No.");
        model.addColumn("Kode Rapid Test");
        model.addColumn("Hasil Test");
        model.addColumn("Biaya Test");
        
        
 
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
       try{
           int no = 1;
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "SELECT * FROM rapid_test";
            
            java.sql.ResultSet res = s.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3)});
                
            }
            tabeldata.setModel(model);
        }catch(Exception e){
            e.printStackTrace();
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    public rapid_test() {
        initComponents();
        tampilkan_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idrapid_txt = new javax.swing.JTextField();
        biaya_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        hapus = new javax.swing.JButton();
        update = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        hasil_txt = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        search_txt = new javax.swing.JTextField();
        cari_btn = new javax.swing.JButton();
        kembali_btn = new javax.swing.JButton();
        count_btn = new javax.swing.JButton();
        count_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dbRSU 1.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Rapid Test");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Kode Rapid Test  :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Hasil Test            :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Biaya Test           :");

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeldata);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Tabel Data Rapid Test");

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hapus.png"))); // NOI18N
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/update.png"))); // NOI18N
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save.png"))); // NOI18N
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        hasil_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Negatif", "Positif" }));
        hasil_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasil_txtActionPerformed(evt);
            }
        });

        jLabel4.setText("*Cari Data Berdasarkan Kode Rapid Test");

        cari_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cari.png"))); // NOI18N
        cari_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_btnActionPerformed(evt);
            }
        });

        kembali_btn.setText("Kembali");
        kembali_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali_btnActionPerformed(evt);
            }
        });

        count_btn.setText("Jumlah Pasien");
        count_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                count_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(idrapid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(hasil_txt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(biaya_txt)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cari_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(count_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(count_btn)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kembali_btn)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addComponent(kembali_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cari_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel7)
                        .addComponent(jLabel4)
                        .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(count_btn)
                            .addComponent(count_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(idrapid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(hasil_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(biaya_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update)
                            .addComponent(simpan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hapus)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "INSERT INTO rapid_test VALUES"+"('"+idrapid_txt.getText()+"','"+hasil_txt.getSelectedItem()+"',"+biaya_txt.getText()+")";
            s.execute(sql);
            //System.out.println("Record Inserted Successfully!");
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
            
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data gagal disimpan!");
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_simpanActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "UPDATE rapid_test SET Id_rptest='"+idrapid_txt.getText()+"',Hasil_rptest='"+hasil_txt.getSelectedItem()+"',Biaya_rptest='"+biaya_txt.getText()+"' WHERE Id_rptest='"+idrapid_txt.getText()+"'";
            
            s.execute(sql);
            //System.out.println("Data berhasil diperbarui!");
            JOptionPane.showMessageDialog(null, "Data berhasil diperbarui!");
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data gagal diperbarui!");
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_updateActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "DELETE FROM rapid_test WHERE Id_rptest='"+idrapid_txt.getText()+"'";
            
            s.execute(sql);
            //System.out.println("Data berhasil dihapus!");
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data gagal dihapus!");
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_hapusActionPerformed

    private void hasil_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasil_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasil_txtActionPerformed

    private void cari_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_btnActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            ResultSet rs;
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "SELECT*FROM rapid_test WHERE Id_rptest='"+search_txt.getText()+"'";
            rs = s.executeQuery(sql);
            if(rs.next()){
                String Id_rptest = rs.getString("Id_rptest");
                String Hasil_rptest = rs.getString("Hasil_rptest");
                String Biaya_rptest = rs.getString("Biaya_rptest");
                
                
                
                idrapid_txt.setText(Id_rptest);
                hasil_txt.setSelectedItem(Hasil_rptest);
                biaya_txt.setText(Biaya_rptest);
                
                
            }
            JOptionPane.showMessageDialog(null,"Data berhasil ditemukan!");
            
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        tampilkan_data();
    }//GEN-LAST:event_cari_btnActionPerformed

    private void kembali_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali_btnActionPerformed
        // TODO add your handling code here:
        tes_covid19 tes = new tes_covid19();
        tes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kembali_btnActionPerformed

    private void count_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_count_btnActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            ResultSet rs;
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "SELECT COUNT(*) FROM rapid_test";
            rs = s.executeQuery(sql);
            if(rs.next()){
                String count = rs.getString("count(*)");
                
                count_txt.setText(count);
            }
            //JOptionPane.showMessageDialog(null,"Data Berhasil Dicari!");
            
        }catch(Exception e){
            e.printStackTrace();
            //JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_count_btnActionPerformed

    private void tabeldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldataMouseClicked
        // TODO add your handling code here:
        int baris = tabeldata.rowAtPoint(evt.getPoint());
        
        String Id_rptest = tabeldata.getValueAt(baris,1).toString();
        idrapid_txt.setText(Id_rptest);
        
        String Hasil_rptest = tabeldata.getValueAt(baris,2).toString();
        hasil_txt.setSelectedItem(Hasil_rptest);
        
        String Biaya_rptest = tabeldata.getValueAt(baris,3).toString();
        biaya_txt.setText(Biaya_rptest);
        
        
    }//GEN-LAST:event_tabeldataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rapid_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rapid_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rapid_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rapid_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rapid_test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biaya_txt;
    private javax.swing.JButton cari_btn;
    private javax.swing.JButton count_btn;
    private javax.swing.JTextField count_txt;
    private javax.swing.JButton hapus;
    private javax.swing.JComboBox<String> hasil_txt;
    private javax.swing.JTextField idrapid_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton kembali_btn;
    private javax.swing.JTextField search_txt;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabeldata;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
