/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package halaman;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZAKI
 */
public class ruang_rawat_inap_covid19 extends javax.swing.JFrame {

    private void kosongkan_form(){
        idruangc19_txt.setEditable(true);
        idruangc19_txt.setText(null);
        idpasien_txt.setText(null);
        ruang_txt.setText(null);
        gedung_txt.setText(null);
        masuk_txt.setText(null);
        keluar_txt.setText(null);
        biaya_txt.setText(null);

        }
      
    private void tampilkan_data(){
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("No.");
        model.addColumn("ID Ruang Covid-19");
        model.addColumn("ID Pasien");
        model.addColumn("Nama Ruang");
        model.addColumn("Nama Gedung");
        model.addColumn("Tanggal Masuk");
        model.addColumn("Tanggal Keluar");
        model.addColumn("Biaya Rawat Inap");
        
 
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
       try{
           int no = 1;
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "SELECT * FROM ruang_rawat_inap_covid19";
            
            java.sql.ResultSet res = s.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
                
            }
            tabeldata.setModel(model);
        }catch(Exception e){
            e.printStackTrace();
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    public ruang_rawat_inap_covid19() {
        initComponents();
        tampilkan_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        idruangc19_txt = new javax.swing.JTextField();
        idpasien_txt = new javax.swing.JTextField();
        ruang_txt = new javax.swing.JTextField();
        gedung_txt = new javax.swing.JTextField();
        masuk_txt = new javax.swing.JTextField();
        keluar_txt = new javax.swing.JTextField();
        biaya_txt = new javax.swing.JTextField();
        hapus = new javax.swing.JButton();
        update = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        search_txt = new javax.swing.JTextField();
        cari_btn = new javax.swing.JButton();
        kembali_btn = new javax.swing.JButton();
        count_btn = new javax.swing.JButton();
        count_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dbRSU 1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Ruang Rawat Inap Covid-19");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 344, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 391, 1946, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("ID Ruang Covid-19 :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 426, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("ID Pasien                :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 470, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Nama Ruang           :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 514, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Nama Gedung         :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 558, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Tanggal Masuk       :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 602, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Tanggal Keluar       :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 646, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Biaya Rawat Inap   :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 690, -1, -1));
        getContentPane().add(idruangc19_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 423, 285, -1));
        getContentPane().add(idpasien_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 467, 285, -1));
        getContentPane().add(ruang_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 511, 284, -1));
        getContentPane().add(gedung_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 555, 284, -1));
        getContentPane().add(masuk_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 599, 285, -1));
        getContentPane().add(keluar_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 643, 284, -1));
        getContentPane().add(biaya_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 687, 283, -1));

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hapus.png"))); // NOI18N
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 788, 155, -1));

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/update.png"))); // NOI18N
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 788, 121, -1));

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save.png"))); // NOI18N
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 788, 121, -1));

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeldata);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 410, 1370, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Tabel Data Ruang Rawat Inap Covid-19");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 344, -1, -1));

        jLabel11.setText("*Cari Data Berdasarkan ID Ruang Covid-19");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1041, 352, -1, -1));
        getContentPane().add(search_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1362, 349, 190, -1));

        cari_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cari.png"))); // NOI18N
        cari_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_btnActionPerformed(evt);
            }
        });
        getContentPane().add(cari_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 344, 90, 30));

        kembali_btn.setText("Kembali");
        kembali_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali_btnActionPerformed(evt);
            }
        });
        getContentPane().add(kembali_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 306, -1, -1));

        count_btn.setText("Jumlah Pasien");
        count_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                count_btnActionPerformed(evt);
            }
        });
        getContentPane().add(count_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1800, 350, -1, -1));
        getContentPane().add(count_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1710, 350, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "INSERT INTO ruang_rawat_inap_covid19 VALUES"+"("+idruangc19_txt.getText()+","+idpasien_txt.getText()+",'"+ruang_txt.getText()+"','"+gedung_txt.getText()+"','"+masuk_txt.getText()+"','"+keluar_txt.getText()+"','"+biaya_txt.getText()+"')";
            s.execute(sql);
            //System.out.println("Data berhasil disimpan!");
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
            
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data gagal disimpan!");
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_simpanActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "UPDATE ruang_rawat_inap_covid19 SET Id_ruang_cov19='"+idruangc19_txt.getText()+"',Id_pasien='"+idpasien_txt.getText()+"',Nama_ruang='"+ruang_txt.getText()+"',Nama_gedung='"+gedung_txt.getText()+"',Tgl_masuk='"+masuk_txt.getText()+"',Tgl_keluar='"+keluar_txt.getText()+"',Biaya_rawatinap='"+biaya_txt.getText()+"' WHERE Id_ruang_cov19='"+idruangc19_txt.getText()+"'";
            
            s.execute(sql);
            //System.out.println("Data berhasil diperbarui!");
            JOptionPane.showMessageDialog(null, "Data berhasil diperbarui!");
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data gagal diperbarui!");
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_updateActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "DELETE FROM ruang_rawat_inap_covid19 WHERE Id_ruang_cov19='"+idruangc19_txt.getText()+"'";
            
            s.execute(sql);
            //System.out.println("Data berhasil dihapus!");
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data gagal dihapus!");
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_hapusActionPerformed

    private void cari_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_btnActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            ResultSet rs;
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "SELECT*FROM ruang_rawat_inap_covid19 WHERE Id_ruang_cov19='"+search_txt.getText()+"'";
            rs = s.executeQuery(sql);
            if(rs.next()){
                String Id_ruang_cov19 = rs.getString("Id_ruang_cov19");
                String Id_pasien = rs.getString("Id_pasien");
                String Nama_ruang = rs.getString("Nama_ruang");
                String Nama_gedung = rs.getString("Nama_gedung");
                String Tgl_masuk = rs.getString("Tgl_masuk");
                String Tgl_keluar = rs.getString("Tgl_keluar");
                String Biaya_rawatinap = rs.getString("Biaya_rawatinap");
                
                
                idruangc19_txt.setText(Id_ruang_cov19);
                idpasien_txt.setText(Id_pasien);
                ruang_txt.setText(Nama_ruang);
                gedung_txt.setText(Nama_gedung);
                masuk_txt.setText(Tgl_masuk);
                keluar_txt.setText(Tgl_keluar);
                biaya_txt.setText(Biaya_rawatinap);
                
            }
            JOptionPane.showMessageDialog(null,"Data berhasil ditemukan!");
            
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        tampilkan_data();
    }//GEN-LAST:event_cari_btnActionPerformed

    private void kembali_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali_btnActionPerformed
        // TODO add your handling code here:
        menu m = new menu();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kembali_btnActionPerformed

    private void count_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_count_btnActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            ResultSet rs;
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "SELECT COUNT(*) FROM ruang_rawat_inap_covid19";
            rs = s.executeQuery(sql);
            if(rs.next()){
                String count = rs.getString("count(*)");
                
                count_txt.setText(count);
            }
            //JOptionPane.showMessageDialog(null,"Data Berhasil Dicari!");
            
        }catch(Exception e){
            e.printStackTrace();
            //JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_count_btnActionPerformed

    private void tabeldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldataMouseClicked
        // TODO add your handling code here:
        int baris = tabeldata.rowAtPoint(evt.getPoint());
        
        String Id_ruang_cov19 = tabeldata.getValueAt(baris,1).toString();
        idruangc19_txt.setText(Id_ruang_cov19);
        
        String Id_pasien = tabeldata.getValueAt(baris,2).toString();
        idpasien_txt.setText(Id_pasien);
        
        String Nama_ruang = tabeldata.getValueAt(baris,3).toString();
        ruang_txt.setText(Nama_ruang);
        
        String Nama_gedung = tabeldata.getValueAt(baris,4).toString();
        gedung_txt.setText(Nama_gedung);
        
        String Tgl_masuk = tabeldata.getValueAt(baris,5).toString();
        masuk_txt.setText(Tgl_masuk);
        
        String Tgl_keluar = tabeldata.getValueAt(baris,5).toString();
        keluar_txt.setText(Tgl_keluar);
        
        String Biaya_rawatinap = tabeldata.getValueAt(baris,5).toString();
        biaya_txt.setText(Biaya_rawatinap);
    }//GEN-LAST:event_tabeldataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ruang_rawat_inap_covid19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ruang_rawat_inap_covid19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ruang_rawat_inap_covid19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ruang_rawat_inap_covid19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ruang_rawat_inap_covid19().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biaya_txt;
    private javax.swing.JButton cari_btn;
    private javax.swing.JButton count_btn;
    private javax.swing.JTextField count_txt;
    private javax.swing.JTextField gedung_txt;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField idpasien_txt;
    private javax.swing.JTextField idruangc19_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField keluar_txt;
    private javax.swing.JButton kembali_btn;
    private javax.swing.JTextField masuk_txt;
    private javax.swing.JTextField ruang_txt;
    private javax.swing.JTextField search_txt;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabeldata;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
