/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package halaman;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZAKI
 */
public class tes_covid19 extends javax.swing.JFrame {

    private void kosongkan_form(){
        idstatusc19_txt.setEditable(true);
        idstatusc19_txt.setText(null);
        idpasien_txt.setText(null);
        idrapid_txt.setText(null);
        idswab_txt.setText(null);;
        statusc19_txt.setSelectedIndex(0);

        }
      
    private void tampilkan_data(){
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("No.");
        model.addColumn("ID Status Covid-19");
        model.addColumn("ID Pasien");
        model.addColumn("Kode Rapid Test");
        model.addColumn("Kode PCR Swab Test");
        model.addColumn("Status Covid-19");    
        
 
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
       try{
           int no = 1;
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "SELECT * FROM status_covid19";
            
            java.sql.ResultSet res = s.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)});
                
            }
            tabeldata.setModel(model);
        }catch(Exception e){
            e.printStackTrace();
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
    public tes_covid19() {
        initComponents();
        tampilkan_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idstatusc19_txt = new javax.swing.JTextField();
        idrapid_txt = new javax.swing.JTextField();
        idswab_txt = new javax.swing.JTextField();
        hapus = new javax.swing.JButton();
        update = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        rapid_btn = new javax.swing.JButton();
        swab_btn = new javax.swing.JButton();
        statusc19_txt = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldata = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idpasien_txt = new javax.swing.JTextField();
        kembali_btn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        search_txt = new javax.swing.JTextField();
        cari_btn = new javax.swing.JButton();
        count_btn = new javax.swing.JButton();
        count_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dbRSU 1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Status Covid-19 Test");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 344, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 394, 1946, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("ID Status Covid-19    :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 423, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Kode Rapid Test        :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 518, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Kode PCR Swab Test :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 583, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Status Covid-19         :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 634, -1, -1));
        getContentPane().add(idstatusc19_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 420, 285, -1));
        getContentPane().add(idrapid_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 515, 287, -1));
        getContentPane().add(idswab_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 580, 283, -1));

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hapus.png"))); // NOI18N
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 817, 155, -1));

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/update.png"))); // NOI18N
        update.setToolTipText("");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 817, 121, -1));

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save.png"))); // NOI18N
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 817, 121, -1));

        rapid_btn.setText("Rapid Test");
        rapid_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rapid_btnActionPerformed(evt);
            }
        });
        getContentPane().add(rapid_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 508, 139, 41));

        swab_btn.setText("PCR Swab Test");
        swab_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swab_btnActionPerformed(evt);
            }
        });
        getContentPane().add(swab_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 573, -1, 40));

        statusc19_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Negatif", "Positif" }));
        getContentPane().add(statusc19_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 631, 284, -1));

        tabeldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeldata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeldata);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 394, 1218, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Tabel Data Status Covid-19");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 344, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("ID Pasien                   :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 467, -1, -1));
        getContentPane().add(idpasien_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 464, 285, -1));

        kembali_btn.setText("Kembali");
        kembali_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali_btnActionPerformed(evt);
            }
        });
        getContentPane().add(kembali_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 306, -1, -1));

        jLabel9.setText("*Cari Berdasarkan ID Status Covid-19");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1056, 352, -1, -1));
        getContentPane().add(search_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1341, 344, 191, -1));

        cari_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cari.png"))); // NOI18N
        cari_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_btnActionPerformed(evt);
            }
        });
        getContentPane().add(cari_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 344, 90, 35));

        count_btn.setText("Jumlah Pasien");
        count_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                count_btnActionPerformed(evt);
            }
        });
        getContentPane().add(count_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1790, 350, -1, -1));
        getContentPane().add(count_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 350, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void swab_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swab_btnActionPerformed
        // TODO add your handling code here:
        pcr_swab_test sw = new pcr_swab_test();
        sw.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_swab_btnActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "INSERT INTO status_covid19 VALUES"+"('"+idstatusc19_txt.getText()+"',"+idpasien_txt.getText()+",'"+idrapid_txt.getText()+"','"+idswab_txt.getText()+"','"+statusc19_txt.getSelectedItem()+"')";
            s.execute(sql);
            //System.out.println("Record Inserted Successfully!");
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
            
        }catch(Exception e){
            e.printStackTrace();
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_simpanActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "UPDATE status_covid19 SET Id_status='"+idstatusc19_txt.getText()+"',Id_pasien='"+idpasien_txt.getText()+"',Id_rptest='"+idrapid_txt.getText()+"',Id_swtest='"+idswab_txt.getText()+"',Status_cov19='"+statusc19_txt.getSelectedItem()+"'"+" WHERE Id_status='"+idstatusc19_txt.getText()+"'";
            
            s.execute(sql);
            //System.out.println("Data berhasil diperbarui!");
            JOptionPane.showMessageDialog(null, "Data berhasil diperbarui!");
        }catch(Exception e){
            e.printStackTrace();
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_updateActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "DELETE FROM status_covid19 WHERE Id_status='"+idstatusc19_txt.getText()+"'";
            
            s.execute(sql);
            //System.out.println("Data berhasil dihapus!");
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
        }catch(Exception e){
            e.printStackTrace();
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        tampilkan_data();
        kosongkan_form();
    }//GEN-LAST:event_hapusActionPerformed

    private void rapid_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rapid_btnActionPerformed
        // TODO add your handling code here:
        rapid_test rp = new rapid_test();
        rp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_rapid_btnActionPerformed

    private void cari_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_btnActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            ResultSet rs;
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "SELECT*FROM status_covid19 WHERE Id_status='"+search_txt.getText()+"'";
            rs = s.executeQuery(sql);
            if(rs.next()){
                String Id_status = rs.getString("Id_status");
                String Id_pasien = rs.getString("Id_Id_pasien");
                String Id_rptest = rs.getString("Id_rptest");
                String Id_swtest = rs.getString("Id_swtest");
                String Status_cov19 = rs.getString("Status_cov19");
                
                
                idstatusc19_txt.setText(Id_status);
                idpasien_txt.setText(Id_pasien);
                idrapid_txt.setText(Id_rptest);
                idswab_txt.setText(Id_swtest);
                statusc19_txt.setSelectedItem(Status_cov19);
                
            }
            JOptionPane.showMessageDialog(null,"Data berhasil ditemukan!");
            
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        tampilkan_data();
    }//GEN-LAST:event_cari_btnActionPerformed

    private void kembali_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali_btnActionPerformed
        // TODO add your handling code here:
        menu m = new menu();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kembali_btnActionPerformed

    private void count_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_count_btnActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement s = null;
        String url = "jdbc:mariadb://localhost:3310/uas_pdb_19650079";
        String user = "root";
        String password = "12345678";
        try{
            ResultSet rs;
            Class.forName("org.mariadb.jdbc.Driver");
            connect = DriverManager.getConnection(url,user,password);
            s = connect.createStatement();
            String sql = "SELECT COUNT(*) FROM status_covid19";
            rs = s.executeQuery(sql);
            if(rs.next()){
                String count = rs.getString("count(*)");
                
                count_txt.setText(count);
            }
            //JOptionPane.showMessageDialog(null,"Data Berhasil Dicari!");
            
        }catch(Exception e){
            e.printStackTrace();
            //JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        }
        try{
            if(connect != null){
                s.close();
                connect.close();
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_count_btnActionPerformed

    private void tabeldataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldataMouseClicked
        // TODO add your handling code here:
        int baris = tabeldata.rowAtPoint(evt.getPoint());
        
        String Id_status = tabeldata.getValueAt(baris,1).toString();
        idstatusc19_txt.setText(Id_status);
        
        String Id_pasien = tabeldata.getValueAt(baris,2).toString();
        idpasien_txt.setText(Id_pasien);
        
        String Id_rptest = tabeldata.getValueAt(baris,3).toString();
        idrapid_txt.setText(Id_rptest);
        
        String Id_swtest = tabeldata.getValueAt(baris,3).toString();
        idswab_txt.setText(Id_swtest);
        
        String Status_cov19 = tabeldata.getValueAt(baris,3).toString();
        statusc19_txt.setSelectedItem(Status_cov19);
    }//GEN-LAST:event_tabeldataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tes_covid19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tes_covid19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tes_covid19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tes_covid19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tes_covid19().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari_btn;
    private javax.swing.JButton count_btn;
    private javax.swing.JTextField count_txt;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField idpasien_txt;
    private javax.swing.JTextField idrapid_txt;
    private javax.swing.JTextField idstatusc19_txt;
    private javax.swing.JTextField idswab_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton kembali_btn;
    private javax.swing.JButton rapid_btn;
    private javax.swing.JTextField search_txt;
    private javax.swing.JButton simpan;
    private javax.swing.JComboBox<String> statusc19_txt;
    private javax.swing.JButton swab_btn;
    private javax.swing.JTable tabeldata;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
